# Generated by Django 4.2.23 on 2025-08-25 06:05

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BIAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold Alert"),
                            ("anomaly", "Anomaly Alert"),
                            ("data_quality", "Data Quality Alert"),
                            ("performance", "Performance Alert"),
                            ("schedule", "Scheduled Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("condition_config", models.JSONField(default=dict)),
                ("notification_config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BIAnalyticsSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("query_history", models.JSONField(default=list)),
                ("visualizations", models.JSONField(default=list)),
                ("insights_discovered", models.JSONField(default=list)),
                ("bookmarks", models.JSONField(default=list)),
                ("collaboration_notes", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_accessed"],
            },
        ),
        migrations.CreateModel(
            name="BIDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("executive", "Executive Summary"),
                            ("sales", "Sales Analytics"),
                            ("financial", "Financial Analytics"),
                            ("operational", "Operational Analytics"),
                            ("customer", "Customer Analytics"),
                            ("product", "Product Analytics"),
                            ("custom", "Custom Dashboard"),
                        ],
                        max_length=50,
                    ),
                ),
                ("layout_config", models.JSONField(default=dict)),
                ("filters_config", models.JSONField(default=dict)),
                ("refresh_interval", models.IntegerField(default=300)),
                ("is_public", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BIDataCatalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("table", "Database Table"),
                            ("view", "Database View"),
                            ("api", "API Endpoint"),
                            ("file", "Data File"),
                            ("stream", "Data Stream"),
                        ],
                        max_length=50,
                    ),
                ),
                ("schema_name", models.CharField(blank=True, max_length=100)),
                ("table_name", models.CharField(blank=True, max_length=100)),
                ("columns_metadata", models.JSONField(default=dict)),
                (
                    "data_quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("data_lineage", models.JSONField(default=dict)),
                ("business_glossary", models.JSONField(default=dict)),
                ("tags", models.JSONField(default=list)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("restricted", "Restricted"),
                            ("confidential", "Confidential"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("update_frequency", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BIDataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("database", "Database Query"),
                            ("api", "API Endpoint"),
                            ("file", "File Upload"),
                            ("external", "External Service"),
                            ("realtime", "Real-time Stream"),
                        ],
                        max_length=50,
                    ),
                ),
                ("connection_config", models.JSONField(default=dict)),
                ("query_template", models.TextField(blank=True)),
                ("schema_definition", models.JSONField(default=dict)),
                (
                    "refresh_schedule",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("1min", "Every Minute"),
                            ("5min", "Every 5 Minutes"),
                            ("15min", "Every 15 Minutes"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("manual", "Manual Only"),
                        ],
                        default="hourly",
                        max_length=50,
                    ),
                ),
                ("last_refresh", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BIInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("anomaly", "Anomaly Detection"),
                            ("trend", "Trend Analysis"),
                            ("correlation", "Correlation Discovery"),
                            ("forecast", "Forecast Alert"),
                            ("threshold", "Threshold Breach"),
                            ("pattern", "Pattern Recognition"),
                            ("recommendation", "Recommendation"),
                            ("alert", "Business Alert"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "expected_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "deviation_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("action_items", models.JSONField(default=list)),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-severity"],
            },
        ),
        migrations.CreateModel(
            name="BIMLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("forecasting", "Sales Forecasting"),
                            ("classification", "Customer Classification"),
                            ("clustering", "Customer Segmentation"),
                            ("anomaly_detection", "Anomaly Detection"),
                            ("recommendation", "Recommendation Engine"),
                            ("churn_prediction", "Churn Prediction"),
                            ("price_optimization", "Price Optimization"),
                            ("demand_planning", "Demand Planning"),
                        ],
                        max_length=50,
                    ),
                ),
                ("algorithm", models.CharField(max_length=100)),
                ("feature_config", models.JSONField(default=dict)),
                ("hyperparameters", models.JSONField(default=dict)),
                ("performance_metrics", models.JSONField(default=dict)),
                ("model_file_path", models.CharField(blank=True, max_length=500)),
                ("version", models.CharField(default="1.0", max_length=50)),
                ("is_deployed", models.BooleanField(default=False)),
                ("deployment_config", models.JSONField(default=dict)),
                ("last_trained", models.DateTimeField(blank=True, null=True)),
                ("last_prediction", models.DateTimeField(blank=True, null=True)),
                (
                    "training_schedule",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BIPerformanceMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric_name", models.CharField(max_length=100)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("query_performance", "Query Performance"),
                            ("dashboard_load_time", "Dashboard Load Time"),
                            ("data_freshness", "Data Freshness"),
                            ("user_engagement", "User Engagement"),
                            ("system_resource", "System Resource Usage"),
                            ("error_rate", "Error Rate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=15)),
                ("unit", models.CharField(max_length=50)),
                ("metadata", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BIReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("executive_summary", "Executive Summary"),
                            ("sales_performance", "Sales Performance"),
                            ("financial_analysis", "Financial Analysis"),
                            ("customer_insights", "Customer Insights"),
                            ("product_analysis", "Product Analysis"),
                            ("operational_metrics", "Operational Metrics"),
                            ("predictive_analytics", "Predictive Analytics"),
                            ("custom_report", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("query_config", models.JSONField(default=dict)),
                ("visualization_config", models.JSONField(default=dict)),
                ("filters_config", models.JSONField(default=dict)),
                ("schedule_config", models.JSONField(default=dict)),
                ("export_formats", models.JSONField(default=list)),
                ("recipients", models.JSONField(default=list)),
                ("is_scheduled", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BIWidget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("metric", "Key Metric"),
                            ("chart", "Chart"),
                            ("table", "Data Table"),
                            ("gauge", "Gauge"),
                            ("map", "Geographic Map"),
                            ("funnel", "Funnel Chart"),
                            ("heatmap", "Heat Map"),
                            ("treemap", "Tree Map"),
                            ("scatter", "Scatter Plot"),
                            ("timeline", "Timeline"),
                            ("custom", "Custom Widget"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_source", models.CharField(max_length=100)),
                ("query_config", models.JSONField(default=dict)),
                ("visualization_config", models.JSONField(default=dict)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=4)),
                ("height", models.IntegerField(default=3)),
                ("refresh_interval", models.IntegerField(default=300)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="CustomerAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.IntegerField()),
                ("customer_email", models.EmailField(max_length=254)),
                ("acquisition_date", models.DateField()),
                (
                    "acquisition_channel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("total_orders", models.IntegerField(default=0)),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "lifetime_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_order_date", models.DateField(blank=True, null=True)),
                ("days_since_last_order", models.IntegerField(default=0)),
                (
                    "churn_probability",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("customer_segment", models.CharField(default="new", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductSalesAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField()),
                ("product_name", models.CharField(max_length=200)),
                ("category_id", models.IntegerField(blank=True, null=True)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date", models.DateField()),
                ("units_sold", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-revenue"],
            },
        ),
        migrations.CreateModel(
            name="SalesAnomalyDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("orders", "Orders"),
                            ("conversion", "Conversion Rate"),
                            ("aov", "Average Order Value"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actual_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "expected_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "deviation_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date", "-severity"],
            },
        ),
        migrations.CreateModel(
            name="SalesCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "predicted_revenue",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("predicted_orders", models.IntegerField()),
                (
                    "confidence_interval_lower",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "confidence_interval_upper",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "model_accuracy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "seasonal_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "trend_factor",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["forecast_date"],
            },
        ),
        migrations.CreateModel(
            name="SalesGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("orders", "Orders"),
                            ("customers", "New Customers"),
                            ("margin", "Gross Margin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("department", models.CharField(blank=True, max_length=50, null=True)),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total_orders", models.IntegerField(default=0)),
                ("total_customers", models.IntegerField(default=0)),
                ("new_customers", models.IntegerField(default=0)),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "gross_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SalesPipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opportunity_name", models.CharField(max_length=200)),
                ("customer_id", models.IntegerField(blank=True, null=True)),
                ("customer_name", models.CharField(max_length=200)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("qualified", "Qualified"),
                            ("proposal", "Proposal"),
                            ("negotiation", "Negotiation"),
                            ("closed_won", "Closed Won"),
                            ("closed_lost", "Closed Lost"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "probability",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("expected_close_date", models.DateField()),
                ("actual_close_date", models.DateField(blank=True, null=True)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Sales"),
                            ("weekly", "Weekly Summary"),
                            ("monthly", "Monthly Report"),
                            ("quarterly", "Quarterly Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipients", models.JSONField(default=list)),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(default=dict)),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                ("next_send", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SalesTerritory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                (
                    "state_province",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cities", models.JSONField(default=list)),
                ("postal_codes", models.JSONField(default=list)),
                (
                    "target_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "current_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("customer_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
