# Generated by Django 4.2.23 on 2025-08-25 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesterritory",
            name="assigned_rep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesreport",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="salespipeline",
            name="sales_rep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesmetrics",
            unique_together={("date",)},
        ),
        migrations.AddField(
            model_name="salesgoal",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesforecast",
            unique_together={("forecast_date", "forecast_type")},
        ),
        migrations.AddField(
            model_name="salescommission",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_commissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salescommission",
            name="sales_rep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productsalesanalytics",
            unique_together={("product_id", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="customeranalytics",
            unique_together={("customer_id",)},
        ),
        migrations.AddField(
            model_name="biwidget",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="analytics.bidashboard",
            ),
        ),
        migrations.AddField(
            model_name="bireport",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bireport",
            name="data_sources",
            field=models.ManyToManyField(
                related_name="reports", to="analytics.bidatasource"
            ),
        ),
        migrations.AddField(
            model_name="bireport",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_reports", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="biperformancemetric",
            name="dashboard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.bidashboard",
            ),
        ),
        migrations.AddField(
            model_name="biperformancemetric",
            name="data_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.bidatasource",
            ),
        ),
        migrations.AddField(
            model_name="biperformancemetric",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="biperformancemetric",
            name="widget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.biwidget",
            ),
        ),
        migrations.AddField(
            model_name="bimlmodel",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bimlmodel",
            name="training_data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_models",
                to="analytics.bidatasource",
            ),
        ),
        migrations.AddField(
            model_name="biinsight",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acknowledged_insights",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="biinsight",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.bidatasource"
            ),
        ),
        migrations.AddField(
            model_name="bidatasource",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bidatacatalog",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_data_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bidatacatalog",
            name="stewards",
            field=models.ManyToManyField(
                blank=True,
                related_name="stewarded_data_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bidashboard",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bidashboard",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_dashboards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bianalyticssession",
            name="data_sources",
            field=models.ManyToManyField(
                related_name="analytics_sessions", to="analytics.bidatasource"
            ),
        ),
        migrations.AddField(
            model_name="bianalyticssession",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_analytics_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bianalyticssession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bialert",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bialert",
            name="data_source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.bidatasource"
            ),
        ),
        migrations.AddField(
            model_name="bialert",
            name="recipients",
            field=models.ManyToManyField(
                related_name="bi_alerts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salescommission",
            unique_together={("sales_rep", "period_start", "period_end")},
        ),
        migrations.AddIndex(
            model_name="biperformancemetric",
            index=models.Index(
                fields=["metric_name", "timestamp"],
                name="analytics_b_metric__5f86cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="biperformancemetric",
            index=models.Index(
                fields=["metric_type", "timestamp"],
                name="analytics_b_metric__82ad2b_idx",
            ),
        ),
    ]
