"""
Core constants for the ecommerce platform.
"""

# User types
USER_TYPE_CUSTOMER = 'customer'
USER_TYPE_SELLER = 'seller'
USER_TYPE_ADMIN = 'admin'

USER_TYPES = [
    (USER_TYPE_CUSTOMER, 'Customer'),
    (USER_TYPE_SELLER, 'Seller'),
    (USER_TYPE_ADMIN, 'Admin'),
]

# Order statuses
ORDER_STATUS_PENDING = 'PENDING'
ORDER_STATUS_CONFIRMED = 'CONFIRMED'
ORDER_STATUS_PROCESSING = 'PROCESSING'
ORDER_STATUS_SHIPPED = 'SHIPPED'
ORDER_STATUS_DELIVERED = 'DELIVERED'
ORDER_STATUS_CANCELLED = 'CANCELLED'
ORDER_STATUS_RETURNED = 'RETURNED'

ORDER_STATUSES = [
    (ORDER_STATUS_PENDING, 'Pending'),
    (ORDER_STATUS_CONFIRMED, 'Confirmed'),
    (ORDER_STATUS_PROCESSING, 'Processing'),
    (ORDER_STATUS_SHIPPED, 'Shipped'),
    (ORDER_STATUS_DELIVERED, 'Delivered'),
    (ORDER_STATUS_CANCELLED, 'Cancelled'),
    (ORDER_STATUS_RETURNED, 'Returned'),
]

# Payment statuses
PAYMENT_STATUS_PENDING = 'PENDING'
PAYMENT_STATUS_PROCESSING = 'PROCESSING'
PAYMENT_STATUS_COMPLETED = 'COMPLETED'
PAYMENT_STATUS_FAILED = 'FAILED'
PAYMENT_STATUS_CANCELLED = 'CANCELLED'
PAYMENT_STATUS_REFUNDED = 'REFUNDED'

PAYMENT_STATUSES = [
    (PAYMENT_STATUS_PENDING, 'Pending'),
    (PAYMENT_STATUS_PROCESSING, 'Processing'),
    (PAYMENT_STATUS_COMPLETED, 'Completed'),
    (PAYMENT_STATUS_FAILED, 'Failed'),
    (PAYMENT_STATUS_CANCELLED, 'Cancelled'),
    (PAYMENT_STATUS_REFUNDED, 'Refunded'),
]

# Address types
ADDRESS_TYPE_HOME = 'HOME'
ADDRESS_TYPE_WORK = 'WORK'
ADDRESS_TYPE_OTHER = 'OTHER'

ADDRESS_TYPES = [
    (ADDRESS_TYPE_HOME, 'Home'),
    (ADDRESS_TYPE_WORK, 'Work'),
    (ADDRESS_TYPE_OTHER, 'Other'),
]

# File upload limits
MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5MB
ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp']

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Cache timeouts (in seconds)
CACHE_TIMEOUT_SHORT = 300  # 5 minutes
CACHE_TIMEOUT_MEDIUM = 1800  # 30 minutes
CACHE_TIMEOUT_LONG = 3600  # 1 hour
CACHE_TIMEOUT_VERY_LONG = 86400  # 24 hours