# Generated by Django 4.2.23 on 2025-08-25 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityTraining",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("training_name", models.CharField(max_length=200)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("security_awareness", "Security Awareness"),
                            ("phishing_simulation", "Phishing Simulation"),
                            ("incident_response", "Incident Response"),
                            ("compliance", "Compliance Training"),
                            ("technical_security", "Technical Security"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("content", models.TextField()),
                ("duration_minutes", models.IntegerField()),
                ("required_for_roles", models.JSONField(default=list)),
                ("completion_criteria", models.JSONField(default=dict)),
                ("certificate_template", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["training_name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityVulnerability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vulnerability_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                            ("accepted_risk", "Accepted Risk"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("cve_id", models.CharField(blank=True, max_length=50)),
                ("affected_systems", models.JSONField(default=list)),
                ("affected_components", models.JSONField(default=list)),
                ("exploit_available", models.BooleanField(default=False)),
                ("patch_available", models.BooleanField(default=False)),
                ("remediation_steps", models.TextField(blank=True)),
                ("workaround", models.TextField(blank=True)),
                (
                    "discovered_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("resolved_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-cvss_score", "-discovered_date"],
            },
        ),
        migrations.CreateModel(
            name="SecurityThreat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("threat_type", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("investigating", "Investigating"),
                            ("mitigated", "Mitigated"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="detected",
                        max_length=20,
                    ),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "target_resource",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("description", models.TextField()),
                ("detection_method", models.CharField(max_length=100)),
                ("threat_indicators", models.JSONField(default=dict)),
                ("mitigation_actions", models.JSONField(default=list)),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityRiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessment_name", models.CharField(max_length=200)),
                ("asset_category", models.CharField(max_length=100)),
                ("asset_description", models.TextField()),
                ("threat_sources", models.JSONField(default=list)),
                ("vulnerabilities", models.JSONField(default=list)),
                ("existing_controls", models.JSONField(default=list)),
                (
                    "likelihood",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "impact",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                    ),
                ),
                ("risk_score", models.FloatField()),
                ("recommended_controls", models.JSONField(default=list)),
                (
                    "residual_risk",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("implemented", "Implemented"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "assessment_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("review_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-risk_score", "-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="SecurityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("policy_name", models.CharField(max_length=200)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("access_control", "Access Control"),
                            ("data_classification", "Data Classification"),
                            ("incident_response", "Incident Response"),
                            ("acceptable_use", "Acceptable Use"),
                            ("password", "Password Policy"),
                            ("encryption", "Encryption"),
                            ("backup", "Backup and Recovery"),
                        ],
                        max_length=50,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("policy_content", models.TextField()),
                ("compliance_requirements", models.JSONField(default=list)),
                ("enforcement_rules", models.JSONField(default=list)),
                ("exceptions", models.JSONField(default=list)),
                ("effective_date", models.DateTimeField()),
                ("review_date", models.DateTimeField()),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="SecurityMonitoringRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_name", models.CharField(max_length=200)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("intrusion_detection", "Intrusion Detection"),
                            ("anomaly_detection", "Anomaly Detection"),
                            ("compliance_monitoring", "Compliance Monitoring"),
                            ("threat_hunting", "Threat Hunting"),
                            ("data_loss_prevention", "Data Loss Prevention"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("testing", "Testing"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("rule_logic", models.TextField()),
                ("conditions", models.JSONField(default=dict)),
                ("actions", models.JSONField(default=list)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("false_positive_rate", models.FloatField(default=0.0)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["rule_name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("incident_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("data_breach", "Data Breach"),
                            ("malware", "Malware"),
                            ("phishing", "Phishing"),
                            ("ddos", "DDoS Attack"),
                            ("unauthorized_access", "Unauthorized Access"),
                            ("insider_threat", "Insider Threat"),
                            ("system_compromise", "System Compromise"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("investigating", "Investigating"),
                            ("contained", "Contained"),
                            ("eradicated", "Eradicated"),
                            ("recovered", "Recovered"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("impact_assessment", models.TextField(blank=True)),
                ("affected_systems", models.JSONField(default=list)),
                ("affected_users", models.JSONField(default=list)),
                ("timeline", models.JSONField(default=list)),
                ("response_actions", models.JSONField(default=list)),
                ("lessons_learned", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_team",
                    models.ManyToManyField(
                        related_name="security_incidents", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("config_name", models.CharField(max_length=200)),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("firewall", "Firewall"),
                            ("antivirus", "Antivirus"),
                            ("ids_ips", "IDS/IPS"),
                            ("siem", "SIEM"),
                            ("dlp", "Data Loss Prevention"),
                            ("encryption", "Encryption"),
                            ("backup", "Backup"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("configuration_data", models.JSONField(default=dict)),
                ("baseline_config", models.JSONField(default=dict)),
                ("compliance_requirements", models.JSONField(default=list)),
                ("last_validated", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("validation_errors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "managed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["config_name"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audit_name", models.CharField(max_length=200)),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("access_control", "Access Control"),
                            ("data_protection", "Data Protection"),
                            ("network_security", "Network Security"),
                            ("application_security", "Application Security"),
                            ("compliance", "Compliance"),
                            ("vulnerability", "Vulnerability Assessment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("scope", models.TextField()),
                ("objectives", models.JSONField(default=list)),
                ("methodology", models.TextField()),
                ("findings", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("compliance_frameworks", models.JSONField(default=list)),
                ("scheduled_date", models.DateTimeField()),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("report_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("security_event", "Security Event"),
                            ("policy_violation", "Policy Violation"),
                            ("anomaly_detected", "Anomaly Detected"),
                            ("compliance_issue", "Compliance Issue"),
                            ("system_health", "System Health"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("investigating", "Investigating"),
                            ("resolved", "Resolved"),
                            ("false_positive", "False Positive"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("source_system", models.CharField(max_length=100)),
                ("event_data", models.JSONField(default=dict)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="security_management.securitymonitoringrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityTrainingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("certificate_issued", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="security_management.securitytraining",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("user", "training")},
            },
        ),
    ]
