# Generated by Django 4.2.23 on 2025-08-25 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apiendpoint",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endpoints",
                to="api_management.apiversion",
            ),
        ),
        migrations.AddField(
            model_name="apidocumentation",
            name="endpoint",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentation",
                to="api_management.apiendpoint",
            ),
        ),
        migrations.AddIndex(
            model_name="apiusagelog",
            index=models.Index(
                fields=["timestamp", "endpoint"], name="api_managem_timesta_866d84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusagelog",
            index=models.Index(
                fields=["api_key", "timestamp"], name="api_managem_api_key_a1f9c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiusagelog",
            index=models.Index(
                fields=["status", "timestamp"], name="api_managem_status_d8c926_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apiratelimit",
            unique_together={("api_key", "endpoint")},
        ),
        migrations.AlterUniqueTogether(
            name="apiperformancemetric",
            unique_together={("endpoint", "date", "hour")},
        ),
        migrations.AlterUniqueTogether(
            name="apiendpoint",
            unique_together={("path", "method", "version")},
        ),
    ]
