# Generated by Django 4.2.23 on 2025-08-15 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internationalization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="currencyexchangerate",
            name="unique_exchange_rate",
        ),
        migrations.RemoveConstraint(
            model_name="internationalshipping",
            name="unique_shipping_service",
        ),
        migrations.RemoveConstraint(
            model_name="localizedcontent",
            name="unique_localized_content",
        ),
        migrations.RemoveConstraint(
            model_name="regionalcompliance",
            name="unique_region_compliance",
        ),
        migrations.RemoveConstraint(
            model_name="translation",
            name="unique_translation",
        ),
        migrations.RenameIndex(
            model_name="currencyexchangerate",
            new_name="internation_from_cu_8266b6_idx",
            old_name="internationa_from_cu_j7k890_idx",
        ),
        migrations.RenameIndex(
            model_name="internationaltaxrule",
            new_name="internation_country_0930f2_idx",
            old_name="internationa_country_f9g012_idx",
        ),
        migrations.RenameIndex(
            model_name="internationaltaxrule",
            new_name="internation_effecti_f22b20_idx",
            old_name="internationa_effecti_h3i456_idx",
        ),
        migrations.RenameIndex(
            model_name="localizedcontent",
            new_name="internation_content_d1b73b_idx",
            old_name="internationa_content_a1b234_idx",
        ),
        migrations.RenameIndex(
            model_name="localizedcontent",
            new_name="internation_languag_368abc_idx",
            old_name="internationa_languag_d5e678_idx",
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="internation_key_e682e3_idx",
            old_name="internationa_key_b8e123_idx",
        ),
        migrations.RenameIndex(
            model_name="translation",
            new_name="internation_languag_56983c_idx",
            old_name="internationa_languag_c4f567_idx",
        ),
        migrations.AlterUniqueTogether(
            name="currencyexchangerate",
            unique_together={("from_currency", "to_currency", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="internationalshipping",
            unique_together={("carrier", "service_name")},
        ),
        migrations.AlterUniqueTogether(
            name="localizedcontent",
            unique_together={("content_type", "content_id", "field_name", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="regionalcompliance",
            unique_together={("region_code", "compliance_type")},
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("key", "language", "context")},
        ),
    ]
