# Generated by Django 4.2.23 on 2025-08-25 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("locked", "Locked"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("fiscal_year", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "financial_accounting_periods",
                "ordering": ["-start_date"],
                "unique_together": {("period_type", "start_date", "end_date")},
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.costcenter",
                    ),
                ),
            ],
            options={
                "db_table": "financial_cost_centers",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("profit_loss", "Profit & Loss Statement"),
                            ("balance_sheet", "Balance Sheet"),
                            ("cash_flow", "Cash Flow Statement"),
                            ("budget_variance", "Budget Variance Report"),
                            ("kpi_dashboard", "KPI Dashboard"),
                            ("cost_center_analysis", "Cost Center Analysis"),
                            ("financial_ratios", "Financial Ratios Report"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("parameters", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accounting_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.accountingperiod",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "financial_reports",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="CashFlowStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("operating", "Operating Activities"),
                            ("investing", "Investing Activities"),
                            ("financing", "Financing Activities"),
                        ],
                        max_length=20,
                    ),
                ),
                ("line_item", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("order_sequence", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accounting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.accountingperiod",
                    ),
                ),
            ],
            options={
                "db_table": "financial_cash_flow",
                "ordering": ["accounting_period", "category", "order_sequence"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "budget_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue Budget"),
                            ("expense", "Expense Budget"),
                            ("capital", "Capital Budget"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "budgeted_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "actual_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "variance_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accounting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.accountingperiod",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.costcenter",
                    ),
                ),
            ],
            options={
                "db_table": "financial_budgets",
                "ordering": ["-accounting_period__start_date"],
            },
        ),
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("cost_of_goods", "Cost of Goods Sold"),
                            ("operating_expense", "Operating Expense"),
                            ("other_income", "Other Income"),
                            ("other_expense", "Other Expense"),
                            ("tax", "Tax"),
                            ("depreciation", "Depreciation"),
                            ("interest", "Interest"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField()),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("order_id", models.CharField(blank=True, max_length=100)),
                ("product_id", models.CharField(blank=True, max_length=100)),
                ("customer_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accounting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.accountingperiod",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financial.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "financial_transactions",
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_date"],
                        name="financial_t_transac_463e97_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="financial_t_transac_a3436b_idx",
                    ),
                    models.Index(
                        fields=["accounting_period"],
                        name="financial_t_account_b22310_idx",
                    ),
                    models.Index(
                        fields=["cost_center"], name="financial_t_cost_ce_172880_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FinancialKPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("gross_margin", "Gross Margin"),
                            ("net_margin", "Net Margin"),
                            ("operating_margin", "Operating Margin"),
                            ("roa", "Return on Assets"),
                            ("roe", "Return on Equity"),
                            ("current_ratio", "Current Ratio"),
                            ("debt_ratio", "Debt Ratio"),
                            ("inventory_turnover", "Inventory Turnover"),
                            ("receivables_turnover", "Receivables Turnover"),
                            ("cash_conversion_cycle", "Cash Conversion Cycle"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "previous_period_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("calculation_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "accounting_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.accountingperiod",
                    ),
                ),
            ],
            options={
                "db_table": "financial_kpis",
                "ordering": ["-accounting_period__start_date", "kpi_type"],
                "unique_together": {("kpi_type", "accounting_period")},
            },
        ),
    ]
