# Generated by Django 4.2.23 on 2025-08-15 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_enhanced_authentication_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordreset",
            options={
                "verbose_name": "Password Reset",
                "verbose_name_plural": "Password Resets",
            },
        ),
        migrations.RemoveIndex(
            model_name="passwordreset",
            name="authenticat_token_h_499884_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverification",
            new_name="authenticat_token_368f59_idx",
            old_name="authenticat_token_499884_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverification",
            new_name="authenticat_expires_af14fb_idx",
            old_name="authenticat_expires_8662be_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverification",
            new_name="authenticat_user_id_467c85_idx",
            old_name="authenticat_user_id_9751b1_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverification",
            new_name="authenticat_created_dfa7fe_idx",
            old_name="authenticat_created_10b06c_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverificationattempt",
            new_name="authenticat_ip_addr_02c1c5_idx",
            old_name="authenticat_ip_addr_936cfe_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverificationattempt",
            new_name="authenticat_email_6aad5c_idx",
            old_name="authenticat_email_467b49_idx",
        ),
        migrations.RenameIndex(
            model_name="emailverificationattempt",
            new_name="authenticat_created_d8a3f2_idx",
            old_name="authenticat_created_5ccc6c_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordreset",
            new_name="authenticat_expires_49bd83_idx",
            old_name="authenticat_expires_8662be_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordreset",
            new_name="authenticat_user_id_d8f30e_idx",
            old_name="authenticat_user_id_9751b1_idx",
        ),
        migrations.RenameIndex(
            model_name="passwordreset",
            new_name="authenticat_created_963861_idx",
            old_name="authenticat_created_10b06c_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="auth_user_is_emai_3a8972_idx",
            old_name="auth_user_is_emai_c40f2e_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="auth_user_last_lo_9a4e95_idx",
            old_name="auth_user_last_lo_936cfe_idx",
        ),
        migrations.RenameIndex(
            model_name="user",
            new_name="auth_user_account_915d36_idx",
            old_name="auth_user_account_467b49_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="authenticat_last_ac_04a1e9_idx",
            old_name="authenticat_last_ac_f427c8_idx",
        ),
        migrations.RenameIndex(
            model_name="usersession",
            new_name="authenticat_ip_addr_d6bbd8_idx",
            old_name="authenticat_ip_addr_1fea71_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.CharField(default=0, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="passwordreset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_resets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="passwordreset",
            index=models.Index(fields=["token"], name="authenticat_token_4b0921_idx"),
        ),
    ]
