# Generated by Django 4.2.23 on 2025-08-23 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("performance_threshold", "Performance Threshold"),
                            ("logging_level", "Logging Level"),
                            ("tracing_enabled", "Tracing Enabled"),
                            ("dashboard_settings", "Dashboard Settings"),
                            ("alert_settings", "Alert Settings"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("config_data", models.JSONField()),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "debugging_configuration",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("login", "User Login"),
                            ("product_fetch", "Product Catalog Access"),
                            ("cart_update", "Cart Operations"),
                            ("checkout", "Checkout Process"),
                            ("order_management", "Order Management"),
                            ("seller_operations", "Seller Operations"),
                            ("admin_operations", "Admin Operations"),
                            ("api_call", "Generic API Call"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("start_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "debugging_workflow_session",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="TraceStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("api", "API"),
                            ("database", "Database"),
                            ("cache", "Cache"),
                            ("external", "External Service"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("component", models.CharField(db_index=True, max_length=100)),
                ("operation", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="started",
                        max_length=20,
                    ),
                ),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "workflow_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trace_steps",
                        to="debugging.workflowsession",
                    ),
                ),
            ],
            options={
                "db_table": "debugging_trace_step",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        choices=[
                            ("response_time", "Response Time (ms)"),
                            ("memory_usage", "Memory Usage (MB)"),
                            ("cpu_usage", "CPU Usage (%)"),
                            ("query_count", "Query Count"),
                            ("cache_hit_rate", "Cache Hit Rate (%)"),
                            ("error_rate", "Error Rate (%)"),
                            ("throughput", "Throughput (req/sec)"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("api", "API"),
                            ("database", "Database"),
                            ("cache", "Cache"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("component", models.CharField(blank=True, max_length=100, null=True)),
                ("warning_threshold", models.FloatField()),
                ("critical_threshold", models.FloatField()),
                ("enabled", models.BooleanField(default=True)),
                ("alert_on_warning", models.BooleanField(default=True)),
                ("alert_on_critical", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "debugging_performance_threshold",
                "ordering": ["layer", "metric_name"],
                "indexes": [
                    models.Index(
                        fields=["metric_name", "layer"],
                        name="debugging_p_metric__90322c_idx",
                    ),
                    models.Index(
                        fields=["enabled", "layer"],
                        name="debugging_p_enabled_e4eade_idx",
                    ),
                ],
                "unique_together": {("metric_name", "layer", "component")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("api", "API"),
                            ("database", "Database"),
                            ("cache", "Cache"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("component", models.CharField(db_index=True, max_length=100)),
                (
                    "metric_name",
                    models.CharField(
                        choices=[
                            ("response_time", "Response Time (ms)"),
                            ("memory_usage", "Memory Usage (MB)"),
                            ("cpu_usage", "CPU Usage (%)"),
                            ("query_count", "Query Count"),
                            ("cache_hit_rate", "Cache Hit Rate (%)"),
                            ("error_rate", "Error Rate (%)"),
                            ("throughput", "Throughput (req/sec)"),
                            ("connection_pool", "Connection Pool Usage"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("metric_value", models.FloatField()),
                ("threshold_warning", models.FloatField(blank=True, null=True)),
                ("threshold_critical", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "debugging_performance_snapshot",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "layer"],
                        name="debugging_p_timesta_21ebdd_idx",
                    ),
                    models.Index(
                        fields=["metric_name", "component"],
                        name="debugging_p_metric__d0f9c5_idx",
                    ),
                    models.Index(
                        fields=["correlation_id", "timestamp"],
                        name="debugging_p_correla_59623e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("api", "API"),
                            ("database", "Database"),
                            ("cache", "Cache"),
                            ("external", "External Service"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("component", models.CharField(db_index=True, max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="error",
                        max_length=20,
                    ),
                ),
                ("error_type", models.CharField(db_index=True, max_length=100)),
                ("error_message", models.TextField()),
                ("stack_trace", models.TextField(blank=True, null=True)),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "debugging_error_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="workflowsession",
            index=models.Index(
                fields=["correlation_id", "start_time"],
                name="debugging_w_correla_6ad8f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowsession",
            index=models.Index(
                fields=["workflow_type", "status"],
                name="debugging_w_workflo_8fd7ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowsession",
            index=models.Index(
                fields=["user", "start_time"], name="debugging_w_user_id_0c6c4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tracestep",
            index=models.Index(
                fields=["workflow_session", "start_time"],
                name="debugging_t_workflo_02937e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tracestep",
            index=models.Index(
                fields=["layer", "component"], name="debugging_t_layer_deeac1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tracestep",
            index=models.Index(
                fields=["status", "duration_ms"], name="debugging_t_status_987f87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["correlation_id", "timestamp"],
                name="debugging_e_correla_8f0c4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["layer", "severity"], name="debugging_e_layer_78b526_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["error_type", "resolved"], name="debugging_e_error_t_1111b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["timestamp", "severity"], name="debugging_e_timesta_35846f_idx"
            ),
        ),
    ]
