# Generated by Django 4.2.23 on 2025-08-24 13:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("debugging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APICallDiscovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("endpoint", models.CharField(db_index=True, max_length=255)),
                ("component_file", models.CharField(max_length=500)),
                ("line_number", models.IntegerField(blank=True, null=True)),
                (
                    "function_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("requires_authentication", models.BooleanField(default=False)),
                ("payload_schema", models.JSONField(blank=True, null=True)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("last_validated", models.DateTimeField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=True)),
                ("validation_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "debugging_api_call_discovery",
                "ordering": ["frontend_route", "endpoint"],
            },
        ),
        migrations.CreateModel(
            name="FrontendRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("page", "Page Route"),
                            ("api", "API Route"),
                            ("dynamic", "Dynamic Route"),
                            ("layout", "Layout Component"),
                            ("loading", "Loading Component"),
                            ("error", "Error Component"),
                            ("not_found", "Not Found Component"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("component_path", models.CharField(max_length=500)),
                ("component_name", models.CharField(max_length=100)),
                ("is_dynamic", models.BooleanField(default=False)),
                ("dynamic_segments", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("last_validated", models.DateTimeField(blank=True, null=True)),
                ("is_valid", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "debugging_frontend_route",
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="RouteDiscoverySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("routes_discovered", models.IntegerField(default=0)),
                ("api_calls_discovered", models.IntegerField(default=0)),
                ("errors_encountered", models.IntegerField(default=0)),
                ("scan_duration_ms", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("error_log", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "debugging_route_discovery_session",
                "ordering": ["-start_time"],
                "indexes": [
                    models.Index(
                        fields=["status", "start_time"],
                        name="debugging_r_status_7ee07b_idx",
                    ),
                    models.Index(
                        fields=["start_time"], name="debugging_r_start_t_f21583_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RouteDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dependency_type", models.CharField(default="direct", max_length=50)),
                ("is_critical", models.BooleanField(default=True)),
                ("load_order", models.IntegerField(default=0)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="debugging.apicalldiscovery",
                    ),
                ),
                (
                    "frontend_route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="debugging.frontendroute",
                    ),
                ),
            ],
            options={
                "db_table": "debugging_route_dependency",
                "ordering": ["frontend_route", "load_order"],
            },
        ),
        migrations.AddIndex(
            model_name="frontendroute",
            index=models.Index(
                fields=["route_type", "is_valid"], name="debugging_f_route_t_0c97f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frontendroute",
            index=models.Index(
                fields=["is_dynamic", "route_type"],
                name="debugging_f_is_dyna_ed8d75_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="frontendroute",
            index=models.Index(
                fields=["discovered_at"], name="debugging_f_discove_d9c18b_idx"
            ),
        ),
        migrations.AddField(
            model_name="apicalldiscovery",
            name="frontend_route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_calls",
                to="debugging.frontendroute",
            ),
        ),
        migrations.AddIndex(
            model_name="routedependency",
            index=models.Index(
                fields=["frontend_route", "is_critical"],
                name="debugging_r_fronten_55eb82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="routedependency",
            index=models.Index(
                fields=["dependency_type", "is_critical"],
                name="debugging_r_depende_751e7c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routedependency",
            unique_together={("frontend_route", "api_call")},
        ),
        migrations.AddIndex(
            model_name="apicalldiscovery",
            index=models.Index(
                fields=["frontend_route", "method"],
                name="debugging_a_fronten_7b36c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apicalldiscovery",
            index=models.Index(
                fields=["endpoint", "method"], name="debugging_a_endpoin_4475f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apicalldiscovery",
            index=models.Index(
                fields=["requires_authentication", "is_valid"],
                name="debugging_a_require_d40d92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apicalldiscovery",
            index=models.Index(
                fields=["discovered_at"], name="debugging_a_discove_7c7dd3_idx"
            ),
        ),
    ]
