# Generated by Django 4.2.23 on 2025-08-25 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("schema", models.JSONField(default=dict)),
                ("validation_rules", models.JSONField(default=dict)),
                ("conditional_logic", models.JSONField(default=dict)),
                ("settings", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_multi_step", models.BooleanField(default=False)),
                ("steps_config", models.JSONField(default=dict)),
                ("auto_save_enabled", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approval_workflow", models.JSONField(default=dict)),
                ("encryption_enabled", models.BooleanField(default=False)),
                ("spam_protection_enabled", models.BooleanField(default=True)),
                ("analytics_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("contact", "Contact Form"),
                            ("survey", "Survey Form"),
                            ("registration", "Registration Form"),
                            ("feedback", "Feedback Form"),
                            ("application", "Application Form"),
                            ("custom", "Custom Form"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("schema", models.JSONField(default=dict)),
                ("settings", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_template", models.BooleanField(default=True)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "form_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("encrypted_data", models.TextField(blank=True)),
                ("files", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("completion_time", models.DurationField(blank=True, null=True)),
                ("is_spam", models.BooleanField(default=False)),
                ("spam_score", models.FloatField(default=0.0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="forms.form",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "form_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="FormIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("webhook", "Webhook"),
                            ("email", "Email"),
                            ("crm", "CRM System"),
                            ("marketing", "Marketing Platform"),
                            ("database", "External Database"),
                            ("api", "REST API"),
                            ("zapier", "Zapier"),
                            ("custom", "Custom Integration"),
                        ],
                        max_length=50,
                    ),
                ),
                ("endpoint_url", models.URLField(blank=True)),
                ("configuration", models.JSONField(default=dict)),
                ("headers", models.JSONField(default=dict)),
                ("field_mapping", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("retry_count", models.PositiveIntegerField(default=3)),
                ("timeout", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "db_table": "form_integrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("step", models.PositiveIntegerField(default=1)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="forms.formsubmission",
                    ),
                ),
            ],
            options={
                "db_table": "form_approval_workflows",
                "ordering": ["step", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormABTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("traffic_split", models.FloatField(default=50.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "success_metric",
                    models.CharField(default="conversion_rate", max_length=50),
                ),
                ("confidence_level", models.FloatField(default=95.0)),
                ("results", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_tests_original",
                        to="forms.form",
                    ),
                ),
                (
                    "variant_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_tests_variant",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "db_table": "form_ab_tests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="form",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="forms.formtemplate",
            ),
        ),
        migrations.CreateModel(
            name="FormVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.CharField(max_length=20)),
                ("schema", models.JSONField(default=dict)),
                ("changes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "db_table": "form_versions",
                "ordering": ["-created_at"],
                "unique_together": {("form", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("textarea", "Textarea"),
                            ("email", "Email"),
                            ("number", "Number"),
                            ("tel", "Phone"),
                            ("url", "URL"),
                            ("password", "Password"),
                            ("select", "Select Dropdown"),
                            ("multiselect", "Multi-Select"),
                            ("radio", "Radio Buttons"),
                            ("checkbox", "Checkboxes"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("time", "Time"),
                            ("file", "File Upload"),
                            ("image", "Image Upload"),
                            ("signature", "Digital Signature"),
                            ("rating", "Rating"),
                            ("slider", "Slider"),
                            ("hidden", "Hidden Field"),
                            ("html", "HTML Content"),
                            ("divider", "Divider"),
                        ],
                        max_length=50,
                    ),
                ),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                ("help_text", models.TextField(blank=True)),
                ("default_value", models.TextField(blank=True)),
                ("options", models.JSONField(default=list)),
                ("validation_rules", models.JSONField(default=dict)),
                ("conditional_logic", models.JSONField(default=dict)),
                ("is_required", models.BooleanField(default=False)),
                ("is_readonly", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("step", models.PositiveIntegerField(default=1)),
                ("css_classes", models.CharField(blank=True, max_length=200)),
                ("attributes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "db_table": "form_fields",
                "ordering": ["order"],
                "unique_together": {("form", "name")},
            },
        ),
        migrations.CreateModel(
            name="FormAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("starts", models.PositiveIntegerField(default=0)),
                ("completions", models.PositiveIntegerField(default=0)),
                ("abandonment_rate", models.FloatField(default=0.0)),
                (
                    "average_completion_time",
                    models.DurationField(blank=True, null=True),
                ),
                ("conversion_rate", models.FloatField(default=0.0)),
                ("field_analytics", models.JSONField(default=dict)),
                ("device_analytics", models.JSONField(default=dict)),
                ("source_analytics", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "db_table": "form_analytics",
                "ordering": ["-date"],
                "unique_together": {("form", "date")},
            },
        ),
    ]
