# Generated by Django 4.2.23 on 2025-08-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_simple_indexes'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='activitylog',
            table_comment='PARTITION BY RANGE (YEAR(created_at)*100 + MONTH(created_at))',
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['admin_user', 'created_at'], name='activity_lo_admin_u_eeaa66_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'created_at'], name='activity_lo_action_0f3584_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['ip_address', 'created_at'], name='activity_lo_ip_addr_4fb53a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['content_type', 'object_id'], name='activity_lo_content_edc5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['module', 'created_at'], name='activity_lo_module_b6aeec_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['severity', 'created_at'], name='activity_lo_severit_5f4b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['is_successful'], name='activity_lo_is_succ_af506e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminloginattempt',
            index=models.Index(fields=['username', 'created_at'], name='admin_login_usernam_1a1a13_idx'),
        ),
        migrations.AddIndex(
            model_name='adminloginattempt',
            index=models.Index(fields=['ip_address', 'created_at'], name='admin_login_ip_addr_292799_idx'),
        ),
        migrations.AddIndex(
            model_name='adminloginattempt',
            index=models.Index(fields=['is_successful'], name='admin_login_is_succ_07d764_idx'),
        ),
        migrations.AddIndex(
            model_name='adminloginattempt',
            index=models.Index(fields=['is_suspicious'], name='admin_login_is_susp_987738_idx'),
        ),
        migrations.AddIndex(
            model_name='adminloginattempt',
            index=models.Index(fields=['admin_user', 'created_at'], name='admin_login_admin_u_3aa89b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='admin_notif_recipie_179dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['notification_type'], name='admin_notif_notific_f1a152_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['priority'], name='admin_notif_priorit_a1ff94_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['scheduled_for'], name='admin_notif_schedul_c2c8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['expires_at'], name='admin_notif_expires_95ee75_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['created_at'], name='admin_notif_created_8e86bb_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpermission',
            index=models.Index(fields=['codename'], name='admin_permi_codenam_2a994d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpermission',
            index=models.Index(fields=['module'], name='admin_permi_module_d718cc_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpermission',
            index=models.Index(fields=['action'], name='admin_permi_action_6fc517_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpermission',
            index=models.Index(fields=['is_active'], name='admin_permi_is_acti_590565_idx'),
        ),
        migrations.AddIndex(
            model_name='adminpermission',
            index=models.Index(fields=['is_sensitive'], name='admin_permi_is_sens_4411e3_idx'),
        ),
        migrations.AddIndex(
            model_name='adminreport',
            index=models.Index(fields=['report_type'], name='admin_repor_report__a07a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='adminreport',
            index=models.Index(fields=['schedule_type'], name='admin_repor_schedul_7ddb02_idx'),
        ),
        migrations.AddIndex(
            model_name='adminreport',
            index=models.Index(fields=['next_run'], name='admin_repor_next_ru_41d7f0_idx'),
        ),
        migrations.AddIndex(
            model_name='adminreport',
            index=models.Index(fields=['is_active'], name='admin_repor_is_acti_3fd55d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminreport',
            index=models.Index(fields=['created_by'], name='admin_repor_created_b29d20_idx'),
        ),
        migrations.AddIndex(
            model_name='adminrole',
            index=models.Index(fields=['name'], name='admin_roles_name_9fb902_idx'),
        ),
        migrations.AddIndex(
            model_name='adminrole',
            index=models.Index(fields=['level'], name='admin_roles_level_d2e32b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminrole',
            index=models.Index(fields=['is_active'], name='admin_roles_is_acti_e1f55d_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['session_key'], name='admin_sessi_session_8e7b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['admin_user', 'is_active'], name='admin_sessi_admin_u_b05938_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['ip_address'], name='admin_sessi_ip_addr_f51801_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['last_activity'], name='admin_sessi_last_ac_36ae03_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['expires_at'], name='admin_sessi_expires_3c8288_idx'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['is_suspicious'], name='admin_sessi_is_susp_83379e_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['email'], name='admin_users_email_91b518_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['role'], name='admin_users_role_6b3116_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['department'], name='admin_users_departm_50df59_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['is_admin_active'], name='admin_users_is_admi_402870_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['last_login_ip'], name='admin_users_last_lo_dbd3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['created_at'], name='admin_users_created_9e09db_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['key'], name='system_sett_key_052b30_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['category'], name='system_sett_categor_db5b74_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['is_public'], name='system_sett_is_publ_c2e919_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['last_modified_by'], name='system_sett_last_mo_232272_idx'),
        ),
    ]
