# Generated by Django 4.2.23 on 2025-08-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_add_advanced_customer_models'),
        ('admin_panel', '0003_comprehensive_order_management'),
    ]

    operations = [
    ]
