# Generated by Django 4.2.23 on 2025-08-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_advanced_inventory_management'),
        ('admin_panel', '0004_merge_20250806_1258'),
    ]

    operations = [
    ]
