# Generated by Django 4.2.23 on 2025-08-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_chart_models"),
        ("admin_panel", "0006_supplier_management_system"),
    ]

    operations = []
