# Generated by Django 4.2.23 on 2025-08-08 07:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('segment_type', models.CharField(choices=[('high_value', 'High Value'), ('frequent_buyer', 'Frequent Buyer'), ('at_risk', 'At Risk'), ('new_customer', 'New Customer'), ('loyal', 'Loyal Customer'), ('dormant', 'Dormant')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('criteria', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'analytics_customer_segments',
            },
        ),
        migrations.CreateModel(
            name='CustomerCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cohort_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('initial_customers', models.IntegerField(default=0)),
                ('current_active_customers', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_customer_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_customer_cohorts',
                'unique_together': {('cohort_date',)},
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('first_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('days_since_last_purchase', models.IntegerField(default=0)),
                ('purchase_frequency', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('customer_lifetime_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('preferred_categories', models.JSONField(default=list)),
                ('preferred_brands', models.JSONField(default=list)),
                ('shopping_patterns', models.JSONField(default=dict)),
                ('churn_risk_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('satisfaction_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_analytics.customersegment')),
            ],
            options={
                'db_table': 'analytics_customer_analytics',
            },
        ),
        migrations.CreateModel(
            name='CustomerSatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.CharField(choices=[('nps', 'Net Promoter Score'), ('csat', 'Customer Satisfaction'), ('ces', 'Customer Effort Score'), ('product_review', 'Product Review'), ('service_feedback', 'Service Feedback')], max_length=20)),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField(default=10)),
                ('feedback_text', models.TextField(blank=True)),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('product_id', models.CharField(blank=True, max_length=50)),
                ('survey_date', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_customer_satisfaction_surveys',
                'indexes': [models.Index(fields=['customer', 'survey_type'], name='analytics_c_custome_2c1a05_idx'), models.Index(fields=['survey_date'], name='analytics_c_survey__e665a8_idx'), models.Index(fields=['score'], name='analytics_c_score_e749a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('product', 'Product Recommendation'), ('category', 'Category Recommendation'), ('brand', 'Brand Recommendation'), ('cross_sell', 'Cross-sell'), ('up_sell', 'Up-sell'), ('reorder', 'Reorder Suggestion')], max_length=20)),
                ('recommended_items', models.JSONField(default=list)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('algorithm_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_customer_recommendations',
                'indexes': [models.Index(fields=['customer', 'recommendation_type'], name='analytics_c_custome_9eae81_idx'), models.Index(fields=['created_at'], name='analytics_c_created_c6c479_idx'), models.Index(fields=['is_active'], name='analytics_c_is_acti_d7d4c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerLifecycleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('prospect', 'Prospect'), ('new', 'New Customer'), ('active', 'Active Customer'), ('at_risk', 'At Risk'), ('dormant', 'Dormant'), ('reactivated', 'Reactivated'), ('churned', 'Churned')], max_length=20)),
                ('stage_date', models.DateTimeField(auto_now_add=True)),
                ('previous_stage', models.CharField(blank=True, choices=[('prospect', 'Prospect'), ('new', 'New Customer'), ('active', 'Active Customer'), ('at_risk', 'At Risk'), ('dormant', 'Dormant'), ('reactivated', 'Reactivated'), ('churned', 'Churned')], max_length=20)),
                ('stage_duration', models.IntegerField(default=0)),
                ('stage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_customer_lifecycle_stages',
                'indexes': [models.Index(fields=['customer', 'stage'], name='analytics_c_custome_438509_idx'), models.Index(fields=['stage_date'], name='analytics_c_stage_d_089323_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerBehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('product_view', 'Product View'), ('add_to_cart', 'Add to Cart'), ('remove_from_cart', 'Remove from Cart'), ('checkout_start', 'Checkout Started'), ('checkout_complete', 'Checkout Completed'), ('search', 'Search'), ('wishlist_add', 'Added to Wishlist'), ('review_submit', 'Review Submitted'), ('support_contact', 'Support Contact')], max_length=20)),
                ('event_data', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_customer_behavior_events',
                'indexes': [models.Index(fields=['customer', 'event_type'], name='analytics_c_custome_760cf7_idx'), models.Index(fields=['timestamp'], name='analytics_c_timesta_a385dd_idx'), models.Index(fields=['session_id'], name='analytics_c_session_dcfad8_idx')],
            },
        ),
    ]
