# Generated by Django 4.2.23 on 2025-08-25 06:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Slot Name")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                (
                    "additional_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Additional Fee",
                    ),
                ),
                (
                    "max_orders",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Maximum Orders"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Delivery Slot",
                "verbose_name_plural": "Delivery Slots",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Tracking Number"
                    ),
                ),
                (
                    "shipping_label_url",
                    models.URLField(blank=True, verbose_name="Shipping Label URL"),
                ),
                (
                    "partner_order_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Partner Order ID"
                    ),
                ),
                (
                    "partner_shipment_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Partner Shipment ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPED", "Shipped"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED_DELIVERY", "Failed Delivery"),
                            ("RETURNED", "Returned"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "estimated_delivery_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Estimated Delivery Date"
                    ),
                ),
                ("shipping_address", models.JSONField(verbose_name="Shipping Address")),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Dimensions"
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Shipping Cost",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Shipped At"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delivered At"
                    ),
                ),
                (
                    "delivery_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="shipping.deliveryslot",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
            },
        ),
        migrations.CreateModel(
            name="ShippingPartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Partner Name")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Partner Code"
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("SHIPROCKET", "Shiprocket"),
                            ("DELHIVERY", "Delhivery"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Partner Type",
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="API Key")),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API Secret"
                    ),
                ),
                ("base_url", models.URLField(verbose_name="API Base URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuration"
                    ),
                ),
                (
                    "supports_cod",
                    models.BooleanField(default=True, verbose_name="Supports COD"),
                ),
                (
                    "supports_prepaid",
                    models.BooleanField(default=True, verbose_name="Supports Prepaid"),
                ),
                (
                    "supports_international",
                    models.BooleanField(
                        default=False, verbose_name="Supports International"
                    ),
                ),
                (
                    "supports_return",
                    models.BooleanField(default=True, verbose_name="Supports Returns"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contact Person"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact Email"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Contact Phone"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Shipping Partner",
                "verbose_name_plural": "Shipping Partners",
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_pin_code",
                    models.CharField(
                        blank=True, max_length=6, verbose_name="Source Pin Code"
                    ),
                ),
                (
                    "destination_pin_code",
                    models.CharField(
                        blank=True, max_length=6, verbose_name="Destination Pin Code"
                    ),
                ),
                (
                    "min_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Minimum Weight (kg)",
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Maximum Weight (kg)",
                    ),
                ),
                (
                    "min_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimum Distance (km)",
                    ),
                ),
                (
                    "max_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Maximum Distance (km)",
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Base Rate"
                    ),
                ),
                (
                    "per_kg_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Per Kg Rate",
                    ),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Per Km Rate",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "shipping_partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_rates",
                        to="shipping.shippingpartner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Rate",
                "verbose_name_plural": "Shipping Rates",
            },
        ),
        migrations.CreateModel(
            name="ShipmentTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPED", "Shipped"),
                            ("IN_TRANSIT", "In Transit"),
                            ("OUT_FOR_DELIVERY", "Out for Delivery"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED_DELIVERY", "Failed Delivery"),
                            ("RETURNED", "Returned"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Location"
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Raw Response"
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_updates",
                        to="shipping.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment Tracking",
                "verbose_name_plural": "Shipment Tracking",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipping_partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="shipping.shippingpartner",
            ),
        ),
        migrations.CreateModel(
            name="ServiceableArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pin_code",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Pin code must be 6 digits", regex="^\\d{6}$"
                            )
                        ],
                        verbose_name="Pin Code",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                (
                    "country",
                    models.CharField(
                        default="India", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "min_delivery_days",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Minimum Delivery Days"
                    ),
                ),
                (
                    "max_delivery_days",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="Maximum Delivery Days"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "shipping_partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serviceable_areas",
                        to="shipping.shippingpartner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviceable Area",
                "verbose_name_plural": "Serviceable Areas",
                "unique_together": {("shipping_partner", "pin_code")},
            },
        ),
    ]
